// Generated by ReScript, PLEASE EDIT WITH CARE


function annotate(it, begin, end) {
  return {
          it: it,
          ann: {
            begin: begin,
            end: end
          }
        };
}

export {
  annotate ,
}
/* No side effect */
